//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkMonHelper.RegistrationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegistrationService.IRegistration")]
    public interface IRegistration {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistration/RegiterNewAccount", ReplyAction="http://tempuri.org/IRegistration/RegiterNewAccountResponse")]
        string RegiterNewAccount(string name, string email, string paypalEmail, string referralCode, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistration/CheckAccount", ReplyAction="http://tempuri.org/IRegistration/CheckAccountResponse")]
        bool CheckAccount(string name, string email, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistration/CheckAccountByRefcode", ReplyAction="http://tempuri.org/IRegistration/CheckAccountByRefcodeResponse")]
        bool CheckAccountByRefcode(string refcode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistrationChannel : InkMonHelper.RegistrationService.IRegistration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrationClient : System.ServiceModel.ClientBase<InkMonHelper.RegistrationService.IRegistration>, InkMonHelper.RegistrationService.IRegistration {
        
        public RegistrationClient() {
        }
        
        public RegistrationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RegiterNewAccount(string name, string email, string paypalEmail, string referralCode, string address) {
            return base.Channel.RegiterNewAccount(name, email, paypalEmail, referralCode, address);
        }
        
        public bool CheckAccount(string name, string email, string address) {
            return base.Channel.CheckAccount(name, email, address);
        }
        
        public bool CheckAccountByRefcode(string refcode) {
            return base.Channel.CheckAccountByRefcode(refcode);
        }
    }
}
